# Generated by Django 5.2.3 on 2025-06-24 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("namae", models.CharField(max_length=128)),
                ("description", models.TextField()),
                (
                    "developer",
                    models.ManyToManyField(
                        related_name="projects_developed", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "manager",
                    models.ManyToManyField(
                        related_name="projects_managed", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tester",
                    models.ManyToManyField(
                        related_name="projects_tested", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
