# Generated by Django 5.2.3 on 2025-06-24 15:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_created_at_project_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="namae",
            new_name="name",
        ),
    ]
