# Generated by Django 5.2.3 on 2025-06-25 04:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_tasks_auditlog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasks",
            old_name="namae",
            new_name="name",
        ),
    ]
