# Generated by Django 5.2.3 on 2025-06-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_options_alter_user_last_login_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, default=None, max_length=254, null=True, unique=True
            ),
        ),
    ]
