# Generated by Django 5.2.3 on 2025-06-24 12:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_email_if_not_null",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_phone_number_if_not_null",
        ),
    ]
